name: C/C++ CI

on:
  [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Build
        run: |
          msbuild msvc/crossauth.sln -p:Configuration=Release /t:Build /p:Platform=Win32

      - name: Deploy
        uses: actions/upload-artifact@v3.1.1
        with:
          name: win32
          path: msvc\Release\crossauth.dll

  linux:
    name: 'Linux'
    runs-on: ubuntu-latest
    container: s1lentq/linux86buildtools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          make
        
      - name: Deploy
        uses: actions/upload-artifact@v3.1.1
        id: upload-job
        with:
          name: linux32
          path: Release/crossauth_mm_i486.so